### ISSUE TITLE
Need to deploy after adding first node to retrieve item list

### ISSUE THREAD

**Issue by fab33** [pdmangel/node-red-contrib-openhab2#13]
As in title with a fresh node-red installation and adding a input node, make configuration and click update, no request is sent to openhab (wireshark confirm this).
And we have this error :
```
TypeError: Cannot read property 'items' of null
    at /home/furax/.node-red/node_modules/node-red-contrib-openhab2/77-openhab2.js:267:20
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/lib/node_modules/node-red/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)
    at /usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:281:22
    at param (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/lib/node_modules/node-red/node_modules/express/lib/router/index.js:275:10)

```

After a first "deploy", it's ok.

**Comment by pdmangel** [comment]
Fixed in version 1.0.8
